# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Entreprenuership\PycharmProjects\task_mgmt_software_alpha_v1\Designs\home_screen_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 741, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(0, 0, 181, 511))
        self.listView.setObjectName("listView")
        self.new_task_button = QtWidgets.QPushButton(self.frame)
        self.new_task_button.setGeometry(QtCore.QRect(20, 150, 141, 41))
        self.new_task_button.setObjectName("new_task_button")
        self.settings_button = QtWidgets.QPushButton(self.frame)
        self.settings_button.setGeometry(QtCore.QRect(20, 210, 141, 41))
        self.settings_button.setObjectName("settings_button")
        self.about_button = QtWidgets.QPushButton(self.frame)
        self.about_button.setGeometry(QtCore.QRect(20, 270, 141, 41))
        self.about_button.setObjectName("about_button")
        self.exit_button = QtWidgets.QPushButton(self.frame)
        self.exit_button.setGeometry(QtCore.QRect(20, 330, 141, 41))
        self.exit_button.setObjectName("exit_button")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 10, 531, 61))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(200, 110, 531, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_task_button.setText(_translate("MainWindow", "New task"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
        self.about_button.setText(_translate("MainWindow", "About"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Task Management Tool"))
